# Generated by Django 5.2.6 on 2025-09-28 09:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("section", models.CharField(blank=True, max_length=20)),
                ("year", models.PositiveIntegerField(default=2025)),
            ],
            options={
                "ordering": ("-year", "name", "section"),
                "unique_together": {("name", "section", "year")},
            },
        ),
        migrations.CreateModel(
            name="GradeSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subjects",
                        to="reportcards.grade",
                    ),
                ),
            ],
            options={
                "ordering": ("grade", "order", "name"),
                "unique_together": {("grade", "name")},
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("year", models.PositiveIntegerField(default=2025)),
            ],
            options={
                "ordering": ("-year", "name"),
                "unique_together": {("name", "year")},
            },
        ),
        migrations.CreateModel(
            name="Marksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=200)),
                (
                    "roll_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("section", models.CharField(blank=True, default="", max_length=50)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "total_obtained",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "total_out_of",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "grade_letter",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=3
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marksheets",
                        to="reportcards.grade",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marksheets",
                        to="reportcards.term",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "student_name"),
                "unique_together": {("grade", "term", "student_name", "roll_number")},
            },
        ),
        migrations.CreateModel(
            name="MarkRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=6
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "grade_letter",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rows",
                        to="reportcards.gradesubject",
                    ),
                ),
                (
                    "marksheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="reportcards.marksheet",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "unique_together": {("marksheet", "subject")},
            },
        ),
    ]
