# Generated by Django 5.2.6 on 2025-09-28 10:29

import reportcards.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportcards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="year",
            field=models.PositiveIntegerField(default=reportcards.models.current_year),
        ),
        migrations.AlterField(
            model_name="term",
            name="year",
            field=models.PositiveIntegerField(default=reportcards.models.current_year),
        ),
    ]
