# Generated by Django 5.2.6 on 2025-09-09 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("path", models.CharField(max_length=512)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("HONEYPOT_HIT", "Honeypot hit"),
                            ("FAILED_LOGIN", "Failed login"),
                            ("BLOCKED", "Blocked"),
                            ("RATE_LIMIT", "Rate limited"),
                        ],
                        max_length=32,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="accounts_se_action_505bcb_idx",
                    ),
                    models.Index(
                        fields=["ip", "created_at"], name="accounts_se_ip_7ad261_idx"
                    ),
                ],
            },
        ),
    ]
