"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-s8(sn((v@cd(hkk=v5k74em22aug)l!24p**2)&iu3(04pm)xq"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


LANGUAGE_CODE = "en"
TIME_ZONE = "Asia/Dhaka"
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ("en", "English"),
    ("bn", "বাংলা"),
]
LOCALE_PATHS = [ BASE_DIR / "locale" ]

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "widget_tweaks",
    'reportcards.apps.ReportcardsConfig',
    "ui",
    "accounts",
    "content",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "content.context_processors.branding",
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "ui.context_processors.footer_settings",
                "ui.context_processors.default_class_id",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [ BASE_DIR / "static" ]  # where your ZIP assets go
STATIC_ROOT = BASE_DIR / "staticfiles"      # for collectstatic later

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"









EMAIL_FILE_PATH = BASE_DIR / "tmp/emails"


EMAIL_BACKEND      = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST         = "smtp.gmail.com"
EMAIL_PORT         = 465
EMAIL_USE_SSL      = True
EMAIL_USE_TLS      = False
EMAIL_HOST_USER    = "nuhad7july02@gmail.com"
EMAIL_HOST_PASSWORD= "rkypyfyuxuqoskzu"  # 16 chars, no spaces
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

PAYMENTS = {
    "SITE_ORIGIN": os.getenv("SITE_ORIGIN", "https://your-domain.com"),

    # bKash PGW (Sandbox creds from bKash portal)
    "BKASH_BASE":      os.getenv("BKASH_BASE", "https://tokenized.sandbox.bka.sh/v1.2.0-beta"),
    "BKASH_USERNAME":  os.getenv("BKASH_USERNAME"),
    "BKASH_PASSWORD":  os.getenv("BKASH_PASSWORD"),
    "BKASH_APP_KEY":   os.getenv("BKASH_APP_KEY"),
    "BKASH_APP_SECRET":os.getenv("BKASH_APP_SECRET"),

    # PayPal (REST)
    "PP_CLIENT": os.getenv("PP_CLIENT"),
    "PP_SECRET": os.getenv("PP_SECRET"),
    "PP_BASE":   os.getenv("PP_BASE", "https://api-m.sandbox.paypal.com"),  # live: https://api-m.paypal.com
}











AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

STAFF_INVITE_TOKEN = os.getenv("STAFF_INVITE_TOKEN", "change-me-please")


SECRET_LOGIN_PREFIX = "x9f83"
SECRET_SIGNUP_PREFIX = "k7p1a"
HONEYPOT_PATH = "admin"


TEACHER_SIGNUP_TOKEN = "teacher-token-1@3"
ADMIN_SIGNUP_TOKEN   = "admin-token-4%6"


CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000", "http://localhost:8000"]

# While you're on HTTP locally:
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

ROLE_STUDENT = "student"
ROLE_TEACHER = "teacher"
ROLE_ADMIN = "admin"




INSTITUTION_NAME = "ScholarsHome"
INSTITUTION_PHONE = "+880-1976250250"
INSTITUTION_EMAIL = "nuhad7july02@gmail.com"
INSTITUTION_ADDRESS = "123 College Road, Sylhet"
INSTITUTION_LOGO_URL = "/static/img/logo.png"






ATTENDANCE_CLASS_MODEL = "content.AcademicClass"
ATTENDANCE_STUDENT_MODEL = "content.Member"













