# Generated by Django 5.2.6 on 2025-09-10 20:41

import content.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=content.models.banner_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="grade",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="notice",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="notices/"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="published_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="section",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="notice",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
