# Generated by Django 5.2.6 on 2025-09-10 20:51

import content.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_banner_image_alter_notice_body_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notice",
            old_name="body",
            new_name="subtitle",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="posted_by",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="section",
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=content.models.banner_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
