# Generated by Django 5.2.6 on 2025-09-10 20:51

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_rename_body_notice_subtitle_remove_notice_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=content.models.banner_upload_to
            ),
        ),
    ]
