# Generated by Django 5.2.6 on 2025-09-11 19:07

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_alter_banner_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="button_link",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=content.models.banner_upload_to
            ),
        ),
    ]
