# Generated by Django 5.2.6 on 2025-09-12 20:04

import content.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_alter_banner_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "YouTube (embed)")],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("place", models.CharField(blank=True, max_length=120)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, upload_to="gallery/")),
                ("youtube_embed_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "-taken_at", "-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="timelineevent",
            options={"ordering": ("date", "order", "-created_at")},
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=content.models.banner_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeline_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
