# Generated by Django 5.2.6 on 2025-09-12 20:21

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_galleryitem_alter_timelineevent_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=content.models.banner_upload_to
            ),
        ),
    ]
