# Generated by Django 5.2.6 on 2025-09-13 19:21

import content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_galleryitem_thumbnail_alter_banner_button_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Section heading shown above the block (e.g., 'About My College').",
                        max_length=150,
                    ),
                ),
                (
                    "college_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional sub-heading inside the block (e.g., your college name).",
                        max_length=150,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Main paragraph text. Keep it concise."
                    ),
                ),
                (
                    "bullets",
                    models.TextField(
                        blank=True,
                        help_text="Bullet points — one per line. Example:\nSmart Classrooms\nExperienced Faculty\nModern Labs",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower comes first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to hide this section."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Sections",
                "ordering": ("order", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="AboutImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload a large image (landscape recommended).",
                        upload_to=content.models.about_upload_to,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Short description for accessibility / alt attribute.",
                        max_length=200,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower shows earlier in the fade sequence."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to hide this image."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Parent About section this image belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.aboutsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Image",
                "verbose_name_plural": "About Images",
                "ordering": ("order", "-created_at"),
            },
        ),
    ]
