# Generated by Django 5.2.6 on 2025-09-13 19:35

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_aboutsection_aboutimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutsection",
            name="image_1",
            field=models.ImageField(
                blank=True,
                help_text="Fading image #1 (landscape recommended).",
                null=True,
                upload_to=content.models.about_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="image_1_alt",
            field=models.CharField(
                blank=True,
                help_text="Alt text for image #1 (accessibility).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="image_2",
            field=models.ImageField(
                blank=True,
                help_text="Fading image #2 (optional).",
                null=True,
                upload_to=content.models.about_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="image_2_alt",
            field=models.CharField(
                blank=True,
                help_text="Alt text for image #2 (accessibility).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="image_3",
            field=models.ImageField(
                blank=True,
                help_text="Fading image #3 (optional).",
                null=True,
                upload_to=content.models.about_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="image_3_alt",
            field=models.CharField(
                blank=True,
                help_text="Alt text for image #3 (accessibility).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="image_4",
            field=models.ImageField(
                blank=True,
                help_text="Fading image #4 (optional).",
                null=True,
                upload_to=content.models.about_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="image_4_alt",
            field=models.CharField(
                blank=True,
                help_text="Alt text for image #4 (accessibility).",
                max_length=200,
            ),
        ),
        migrations.DeleteModel(
            name="AboutImage",
        ),
    ]
