# Generated by Django 5.2.6 on 2025-09-14 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_aboutsection_image_1_aboutsection_image_1_alt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicCalendarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("date_text", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "icon_class",
                    models.CharField(
                        default="bi bi-calendar-event",
                        help_text="CSS class for the icon. Examples:\nBootstrap Icons → bi bi-calendar-week\nFont Awesome 6 → fa-solid fa-calendar-days",
                        max_length=80,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("red", "Red"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                        ],
                        default="blue",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Calendar Item",
                "verbose_name_plural": "Academic Calendar Items",
                "ordering": ("order", "-updated_at"),
            },
        ),
    ]
