# Generated by Django 5.2.6 on 2025-09-14 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0012_academiccalendaritem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="academiccalendaritem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Auto-filled on first save.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendar_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="academiccalendaritem",
            name="date_text",
            field=models.CharField(
                help_text="Human-friendly date or range (e.g., ‘10 Sep 2025’ or ‘20 Dec 2025 – 5 Jan 2026’).",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="academiccalendaritem",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional brief description shown under the date."
            ),
        ),
        migrations.AlterField(
            model_name="academiccalendaritem",
            name="icon_class",
            field=models.CharField(
                default="bi bi-calendar-event",
                help_text="CSS class for the icon.\n• Bootstrap Icons (load BI in base.html): e.g. bi bi-calendar-week\n• Font Awesome (if you load FA): e.g. fa-solid fa-calendar-days",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="academiccalendaritem",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Uncheck to hide this item from the site."
            ),
        ),
        migrations.AlterField(
            model_name="academiccalendaritem",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first."
            ),
        ),
        migrations.AlterField(
            model_name="academiccalendaritem",
            name="title",
            field=models.CharField(
                help_text="Short heading (e.g., ‘Semester Start’).", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="academiccalendaritem",
            name="tone",
            field=models.CharField(
                choices=[
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("red", "Red"),
                    ("purple", "Purple"),
                    ("orange", "Orange"),
                ],
                default="blue",
                help_text="Color accent for the round icon badge.",
                max_length=10,
            ),
        ),
    ]
