# Generated by Django 5.2.6 on 2025-09-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0013_alter_academiccalendaritem_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("science", "Science"),
                            ("commerce", "Commerce"),
                            ("arts", "Arts"),
                            ("vocational", "Vocational"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration", models.CharField(max_length=50)),
                ("shift", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("eligibility", models.CharField(max_length=100)),
                ("monthly_fee", models.IntegerField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="courses/"),
                ),
                (
                    "syllabus_file",
                    models.FileField(blank=True, null=True, upload_to="syllabi/"),
                ),
            ],
        ),
    ]
