# Generated by Django 5.2.6 on 2025-09-14 11:23

import content.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0014_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("order", "title"),
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="course",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower appears first."
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("science", "Science"),
                    ("commerce", "Commerce"),
                    ("arts", "Arts"),
                    ("vocational", "Vocational"),
                ],
                help_text="Used by the front-end filter buttons.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short paragraph shown on the card."
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.CharField(
                blank=True, help_text='Example: "2 years"', max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="eligibility",
            field=models.CharField(
                blank=True, help_text='Example: "SSC pass (GPA ≥ 3.0)"', max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Card image shown at the top.",
                null=True,
                upload_to=content.models.course_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="monthly_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly fee in BDT. Leave blank if not applicable.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="shift",
            field=models.CharField(
                blank=True,
                help_text='Example: "Day", "Morning", "Evening"',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="syllabus_file",
            field=models.FileField(
                blank=True,
                help_text="Optional PDF to open with 'View Syllabus (PDF)'.",
                null=True,
                upload_to=content.models.course_syllabus_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                help_text="Visible title of the course/program (e.g., “HSC – Science”).",
                max_length=150,
            ),
        ),
    ]
