# Generated by Django 5.2.6 on 2025-09-14 13:55

import content.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0015_alter_course_options_course_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("guardian_name", models.CharField(blank=True, max_length=150)),
                ("guardian_phone", models.CharField(blank=True, max_length=30)),
                (
                    "shift",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("day", "Day"),
                            ("morning", "Morning"),
                            ("evening", "Evening"),
                        ],
                        max_length=20,
                    ),
                ),
                ("previous_school", models.CharField(blank=True, max_length=150)),
                (
                    "ssc_gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=content.models.admission_photo_upload_to,
                    ),
                ),
                (
                    "transcript",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=content.models.admission_doc_upload_to,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("review", "In review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admissions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "desired_course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Course the applicant is applying for.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="content.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission Application",
                "verbose_name_plural": "Admission Applications",
                "ordering": ("-created_at",),
            },
        ),
    ]
