# Generated by Django 5.2.6 on 2025-09-15 19:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0016_admissionapplication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admissionapplication",
            options={},
        ),
        migrations.RemoveField(
            model_name="admissionapplication",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="admissionapplication",
            name="status",
        ),
        migrations.RemoveField(
            model_name="admissionapplication",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="add_bus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="add_hostel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="add_marksheet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="fee_admission",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="fee_bus",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="fee_exam",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="fee_hostel",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="fee_marksheet",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="fee_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="fee_tuition",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="payment_method",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="payment_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="admission_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="bus_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="exam_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="first_month_tuition",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="hostel_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="marksheet_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="desired_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="content.course",
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="full_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="guardian_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="guardian_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="admissions/photos/"
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="previous_school",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="shift",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="transcript",
            field=models.FileField(
                blank=True, null=True, upload_to="admissions/transcripts/"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="monthly_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly fee in BDT (for display).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                help_text='Visible title of the course/program (e.g., "HSC – Science").',
                max_length=150,
            ),
        ),
    ]
