# Generated by Django 5.2.6 on 2025-09-15 20:28

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0017_alter_admissionapplication_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ("order", "title")},
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("science", "Science"),
                    ("commerce", "Commerce"),
                    ("arts", "Arts"),
                    ("vocational", "Vocational"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="course",
            name="eligibility",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=content.models.course_image_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="monthly_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="shift",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="course",
            name="syllabus_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=content.models.course_syllabus_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
