# Generated by Django 5.0.6 on 2025-09-16 11:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0018_alter_course_options_alter_course_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionapplication",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="admissionapplication",
            name="payment_paid_at",
        ),
        migrations.RemoveField(
            model_name="admissionapplication",
            name="payment_reference",
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="add_admission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="add_exam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="add_tuition",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="fee_base_subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="fee_selected_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
