# Generated by Django 5.2.6 on 2025-09-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0019_remove_admissionapplication_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionapplication",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="payment_provider",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="payment_txn_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
