# Generated by Django 5.2.6 on 2025-09-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0020_admissionapplication_paid_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="functions/")),
                ("place", models.CharField(blank=True, max_length=200)),
                ("date_text", models.CharField(blank=True, max_length=120)),
                ("time_text", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower shows first"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "-id"],
            },
        ),
    ]
