# Generated by Django 5.2.6 on 2025-09-22 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0021_functionhighlight"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CulturalFestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Cultural Fest 2025", max_length=200),
                ),
                ("description", models.TextField(blank=True)),
                ("place", models.CharField(blank=True, max_length=200)),
                (
                    "date_text",
                    models.CharField(
                        blank=True, help_text="e.g. February 15, 2025", max_length=200
                    ),
                ),
                (
                    "time_text",
                    models.CharField(
                        blank=True, help_text="e.g. 6:00 PM onwards", max_length=200
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="fest_videos/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Direct MP4 link or YouTube/Vimeo URL"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="fest_thumbs/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cultural Fest item",
                "verbose_name_plural": "Cultural Fest items",
                "ordering": ("order", "-created_at"),
            },
        ),
    ]
