# Generated by Django 5.2.6 on 2025-09-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0023_collegefestival_festivalmedia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collegefestival",
            name="hero_youtube_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="festivalmedia",
            name="kind",
            field=models.CharField(
                choices=[("image", "Image"), ("youtube", "YouTube")],
                default="image",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="festivalmedia",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="festivals/thumbs/"
            ),
        ),
        migrations.AddField(
            model_name="festivalmedia",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="festivalmedia",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="festivals/gallery/"
            ),
        ),
    ]
