# Generated by Django 5.2.6 on 2025-09-22 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0025_member"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(default="Contact Us", max_length=120)),
                (
                    "blurb",
                    models.TextField(
                        blank=True,
                        default="We’d love to hear from you! Reach out using the form or visit us directly.",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="123 College Road, Dhaka, Bangladesh",
                        max_length=255,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="+880 123 456 789", max_length=64
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="info@yourcollege.com", max_length=254
                    ),
                ),
                (
                    "hours",
                    models.CharField(
                        blank=True, default="Mon–Sat: 8:00 AM – 5:00 PM", max_length=120
                    ),
                ),
                (
                    "map_embed_url",
                    models.TextField(
                        blank=True,
                        help_text="Paste the full Google Maps <iframe> src URL.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Block",
                "verbose_name_plural": "Contact Block",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=180)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
