# Generated by Django 5.2.6 on 2025-09-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0026_contactinfo_contactmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactinfo",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="blurb",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="map_embed_url",
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="map_input",
            field=models.TextField(
                blank=True,
                help_text="Paste any Google Maps link OR 'lat,lng' (e.g. 24.902362,91.918054). We’ll auto-convert to a clean embed.",
            ),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="map_zoom",
            field=models.PositiveSmallIntegerField(default=17),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="hours",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="phone",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
