# Generated by Django 5.2.6 on 2025-09-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0027_alter_contactinfo_options_remove_contactinfo_blurb_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactinfo",
            options={},
        ),
        migrations.RenameField(
            model_name="contactmessage",
            old_name="is_resolved",
            new_name="handled",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="map_input",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="map_zoom",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="title",
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="handled_by",
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="resolved_at",
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="map_embed_src",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="website",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="hours",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
