# Generated by Django 5.2.6 on 2025-09-23 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0028_alter_contactinfo_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "title",
                    models.CharField(default="Titu BD Science College", max_length=120),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("link_home_enabled", models.BooleanField(default=True)),
                (
                    "link_admission_label",
                    models.CharField(default="Admission", max_length=80),
                ),
                ("link_admission_url", models.URLField(blank=True)),
                (
                    "link_results_label",
                    models.CharField(default="Results", max_length=80),
                ),
                ("link_results_url", models.URLField(blank=True)),
                (
                    "link_events_label",
                    models.CharField(default="Events (Highlights)", max_length=80),
                ),
                (
                    "link_events_anchor",
                    models.CharField(default="#college-functions", max_length=120),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("whatsapp_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("email_linkto", models.EmailField(blank=True, max_length=254)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="footer/")),
                ("logo_url", models.URLField(blank=True)),
                (
                    "copyright_name",
                    models.CharField(default="Titu BD Science College", max_length=160),
                ),
                ("developer_name", models.CharField(default="DS", max_length=160)),
                (
                    "developer_url",
                    models.URLField(blank=True, default="https://t2bd.com"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="footer_settings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Settings",
                "verbose_name_plural": "Footer Settings",
            },
        ),
    ]
