# Generated by Django 5.2.6 on 2025-09-23 10:29

import content.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0029_footersettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admissionapplication",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Admission Application",
                "verbose_name_plural": "Admission Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="collegefestival",
            options={
                "ordering": ("order", "-created_at"),
                "verbose_name": "College Festival",
                "verbose_name_plural": "College Festivals",
            },
        ),
        migrations.AlterModelOptions(
            name="contactinfo",
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Info",
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("order", "title"),
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="festivalmedia",
            options={
                "ordering": ("order", "id"),
                "verbose_name": "Festival Media",
                "verbose_name_plural": "Festival Media",
            },
        ),
        migrations.AlterModelOptions(
            name="functionhighlight",
            options={
                "ordering": ["order", "-id"],
                "verbose_name": "Function Highlight",
                "verbose_name_plural": "Function Highlights",
            },
        ),
        migrations.AlterModelOptions(
            name="member",
            options={
                "ordering": ("order", "name"),
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
            },
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="add_admission",
            field=models.BooleanField(
                default=False, help_text="Include Admission fee row in snapshot."
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="add_bus",
            field=models.BooleanField(
                default=False, help_text="Applicant opts for transport service."
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="add_exam",
            field=models.BooleanField(
                default=False, help_text="Include Exam fee row in snapshot."
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="add_hostel",
            field=models.BooleanField(
                default=False, help_text="Applicant opts for hostel/accommodation."
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="add_marksheet",
            field=models.BooleanField(
                default=False,
                help_text="Applicant opts for marksheet/certification processing.",
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="add_tuition",
            field=models.BooleanField(
                default=False, help_text="Include First Month Tuition row in snapshot."
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Present address with district/upazila for correspondence.",
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this application was submitted."
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Optional, used for record verification.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="desired_course",
            field=models.ForeignKey(
                blank=True,
                help_text="The course the applicant is applying to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="content.course",
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Applicant’s email (optional, but helps for communication).",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_admission",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Snapshot of admission fee at submit time.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_base_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Admission + First Month Tuition + Exam (if chosen).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_bus",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Snapshot of transport fee at submit time.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_exam",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Snapshot of exam fee at submit time.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_hostel",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Snapshot of hostel fee at submit time.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_marksheet",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Snapshot of marksheet fee at submit time.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_selected_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total of all selected rows (base + add-ons).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Legacy total; prefer fee_selected_total.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_tuition",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Snapshot of first-month tuition at submit time.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="full_name",
            field=models.CharField(
                help_text="Applicant’s full legal name.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="guardian_name",
            field=models.CharField(
                blank=True,
                help_text="Parent/guardian full name (optional).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="guardian_phone",
            field=models.CharField(
                blank=True,
                help_text="Parent/guardian phone number (optional).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="message",
            field=models.TextField(
                blank=True, help_text="Any additional information or questions."
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="paid_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp recorded when payment_status becomes Paid.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="payment_provider",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'paypal', 'bkash' (set when payment succeeds).",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of the application payment, if any.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="payment_txn_id",
            field=models.CharField(
                blank=True, help_text="Gateway transaction/capture ID.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="phone",
            field=models.CharField(
                help_text="Primary contact number (WhatsApp preferred if available).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Passport-size photo (optional in demo).",
                null=True,
                upload_to="admissions/photos/",
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="previous_school",
            field=models.CharField(
                blank=True,
                help_text="Last attended school/college (optional).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="shift",
            field=models.CharField(
                blank=True,
                help_text="Preferred shift (Morning/Day/Evening).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="ssc_gpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Secondary exam GPA (or equivalent), if applicable.",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="transcript",
            field=models.FileField(
                blank=True,
                help_text="Academic transcript/certificate (optional).",
                null=True,
                upload_to="admissions/transcripts/",
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this festival record was created."
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="festivals_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="date_text",
            field=models.CharField(
                blank=True,
                help_text="Friendly date (e.g., 'Feb 15, 2025').",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="description",
            field=models.TextField(blank=True, help_text="Festival summary/notes."),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Hero image for the festival card/header (optional).",
                null=True,
                upload_to="festivals/hero/",
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="hero_video",
            field=models.FileField(
                blank=True,
                help_text="Upload an MP4 (or similar) to play in modal (optional).",
                null=True,
                upload_to="festivals/video/",
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="hero_youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Paste any YouTube link (watch/shorts/embed/youtu.be).",
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Untick to hide this festival."
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first across all festivals."
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="place",
            field=models.CharField(
                blank=True, help_text="Venue/location (optional).", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="slug",
            field=models.SlugField(
                help_text="Unique slug for links. Auto-fill from title if unsure.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="time_text",
            field=models.CharField(
                blank=True,
                help_text="Friendly time (e.g., '6:00 PM onwards').",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="title",
            field=models.CharField(
                help_text="Festival title as shown on cards and headers.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="collegefestival",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this festival record was last updated."
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Street address and city/district.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Public contact email.", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="hours",
            field=models.CharField(
                blank=True,
                help_text="Opening hours (e.g., 'Mon–Sat: 8:00 AM – 5:00 PM').",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Untick to stop showing this record on the site.",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="map_embed_src",
            field=models.TextField(
                blank=True,
                help_text="Paste a Google Maps <iframe> src URL or an embeddable map URL.",
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Primary phone number (can include multiple, separated by commas).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated."
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this message was received."
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(
                help_text="Sender’s email address.", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="handled",
            field=models.BooleanField(
                default=False,
                help_text="Tick when the message has been replied to/resolved.",
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(help_text="The user’s message or inquiry."),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(help_text="Sender’s name.", max_length=120),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Optional phone number for follow-up.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(
                help_text="Short subject line for the message.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="website",
            field=models.CharField(
                blank=True,
                help_text="Honeypot anti-spam (should stay empty for humans).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="admission_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="One-time admission/registration fee.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="bus_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Optional transport/bus fee (per month or fixed).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("science", "Science"),
                    ("commerce", "Commerce"),
                    ("arts", "Arts"),
                    ("vocational", "Vocational"),
                ],
                help_text="Bucket used for filtering and grouping courses.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created."
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record (set automatically).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A short overview of what the course covers and outcomes.",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.CharField(
                blank=True,
                help_text="e.g., '2 years', 'Jan–Dec', or 'Semester based'.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="eligibility",
            field=models.CharField(
                blank=True,
                help_text="Minimum requirements (e.g., 'SSC pass with GPA ≥ 3.5').",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="exam_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Internal/board exam fee (if applicable).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="first_month_tuition",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Tuition fee for the first month (or initial installment).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="hostel_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Optional hostel/accommodation fee.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional cover image for cards/headers (recommended landscape).",
                null=True,
                upload_to=content.models.course_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Untick to hide this course from the website."
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="marksheet_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Optional marksheet/certification processing fee.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="monthly_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Legacy field. Prefer the explicit fee fields above.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first in listings."
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="shift",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'Morning', 'Day', 'Evening' (optional).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="syllabus_file",
            field=models.FileField(
                blank=True,
                help_text="Attach a PDF/DOC syllabus students can download.",
                null=True,
                upload_to=content.models.course_syllabus_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                help_text="Public name of the course as shown on the website.",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated."
            ),
        ),
        migrations.AlterField(
            model_name="festivalmedia",
            name="caption",
            field=models.CharField(
                blank=True,
                help_text="Short caption or credit for the media item.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="festivalmedia",
            name="festival",
            field=models.ForeignKey(
                help_text="Festival this media belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_items",
                to="content.collegefestival",
            ),
        ),
        migrations.AlterField(
            model_name="festivalmedia",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload the image (required if kind=Image).",
                null=True,
                upload_to="festivals/gallery/",
            ),
        ),
        migrations.AlterField(
            model_name="festivalmedia",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Untick to hide this media item."
            ),
        ),
        migrations.AlterField(
            model_name="festivalmedia",
            name="kind",
            field=models.CharField(
                choices=[("image", "Image"), ("youtube", "YouTube")],
                default="image",
                help_text="Choose 'Image' for uploads or 'YouTube' for embedded videos.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="festivalmedia",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lower numbers appear first within the festival gallery.",
            ),
        ),
        migrations.AlterField(
            model_name="festivalmedia",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Optional thumbnail (otherwise we try to display the original).",
                null=True,
                upload_to="festivals/thumbs/",
            ),
        ),
        migrations.AlterField(
            model_name="festivalmedia",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Paste any YouTube link (required if kind=YouTube).",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="address",
            field=models.CharField(
                blank=True, help_text="Footer contact address.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="copyright_name",
            field=models.CharField(
                default="Titu BD Science College",
                help_text="Name displayed in copyright line.",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this footer record was created."
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this footer config (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="footer_settings_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="developer_name",
            field=models.CharField(
                default="DS", help_text="Developer/vendor credit name.", max_length=160
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="developer_url",
            field=models.URLField(
                blank=True,
                default="https://t2bd.com",
                help_text="Link for the developer credit.",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Footer email address.", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="email_linkto",
            field=models.EmailField(
                blank=True,
                help_text="Different contact email for the mail icon (defaults to footer email).",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="facebook_url",
            field=models.URLField(blank=True, help_text="Link to your Facebook page."),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Only active records are considered on the website.",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="link_admission_label",
            field=models.CharField(
                default="Admission",
                help_text="Text label for the Admission link.",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="link_admission_url",
            field=models.URLField(
                blank=True, help_text="URL to your admission page/form."
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="link_events_anchor",
            field=models.CharField(
                default="#college-functions",
                help_text="Anchor or URL to your events/highlights section.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="link_events_label",
            field=models.CharField(
                default="Events (Highlights)",
                help_text="Text label for the Events anchor link.",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="link_home_enabled",
            field=models.BooleanField(default=True, help_text="Include the Home link."),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="link_results_label",
            field=models.CharField(
                default="Results",
                help_text="Text label for the Results link.",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="link_results_url",
            field=models.URLField(
                blank=True, help_text="URL to your results portal/page."
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Footer brand/logo image (small).",
                null=True,
                upload_to="footer/",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="logo_url",
            field=models.URLField(
                blank=True,
                help_text="Remote logo URL if you don't want to upload a file.",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Footer phone (can include multiple, separated by commas).",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="title",
            field=models.CharField(
                default="Titu BD Science College",
                help_text="Display title/brand next to contact info.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="twitter_url",
            field=models.URLField(
                blank=True, help_text="Link to your Twitter/X profile."
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this footer record was last updated."
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="whatsapp_url",
            field=models.URLField(
                blank=True, help_text="Link to your WhatsApp (group/business/profile)."
            ),
        ),
        migrations.AlterField(
            model_name="functionhighlight",
            name="date_text",
            field=models.CharField(
                blank=True,
                help_text="Human-friendly date (e.g., 'December 20, 2025').",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="functionhighlight",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short description shown beside the image."
            ),
        ),
        migrations.AlterField(
            model_name="functionhighlight",
            name="image",
            field=models.ImageField(
                help_text="Primary image for this highlight.", upload_to="functions/"
            ),
        ),
        migrations.AlterField(
            model_name="functionhighlight",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Untick to hide this highlight from the site."
            ),
        ),
        migrations.AlterField(
            model_name="functionhighlight",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first."
            ),
        ),
        migrations.AlterField(
            model_name="functionhighlight",
            name="place",
            field=models.CharField(
                blank=True, help_text="Venue/location (optional).", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="functionhighlight",
            name="time_text",
            field=models.CharField(
                blank=True,
                help_text="Human-friendly time (e.g., '4:00 PM onwards').",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="functionhighlight",
            name="title",
            field=models.CharField(
                help_text="Headline for the function highlight (shown over the image).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Short bio/intro (optional, shown in detail cards).",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this profile was created."
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Untick to hide this member from listings."
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(help_text="Full display name.", max_length=120),
        ),
        migrations.AlterField(
            model_name="member",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first within the same role."
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a headshot (square images look best).",
                null=True,
                upload_to="members/",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="photo_url",
            field=models.URLField(
                blank=True, help_text="Remote image URL if you prefer not to upload."
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="post",
            field=models.CharField(
                blank=True,
                help_text="Designation/position (e.g., Professor, Lab Assistant).",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("hod", "Head of Department"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("staff", "Staff"),
                ],
                help_text="Which group this member belongs to.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="section",
            field=models.CharField(
                blank=True,
                help_text="Student section if relevant (e.g., 'A').",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this profile was last updated."
            ),
        ),
    ]
