# Generated by Django 5.2.6 on 2025-09-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0031_gallerypost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="AcademicClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("section", models.CharField(blank=True, max_length=20)),
                ("year", models.PositiveIntegerField(default=2025)),
            ],
            options={
                "ordering": ("-year", "name", "section"),
                "unique_together": {("name", "section", "year")},
            },
        ),
        migrations.CreateModel(
            name="ExamTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("year", models.PositiveIntegerField(default=2025)),
                ("start_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-year", "name"),
                "unique_together": {("name", "year")},
            },
        ),
        migrations.CreateModel(
            name="ClassResultSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_students", models.PositiveIntegerField(default=0)),
                (
                    "appeared",
                    models.PositiveIntegerField(
                        default=0, help_text="Students who appeared for this term."
                    ),
                ),
                (
                    "pass_rate_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="e.g. 76.50",
                        max_digits=5,
                    ),
                ),
                (
                    "overall_avg_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average % across subjects.",
                        max_digits=5,
                    ),
                ),
                (
                    "highest_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Highest % in class.",
                        max_digits=5,
                    ),
                ),
                (
                    "lowest_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Lowest % in class.",
                        max_digits=5,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "klass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_summaries",
                        to="content.academicclass",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_summaries",
                        to="content.examterm",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("klass", "term")},
            },
        ),
        migrations.CreateModel(
            name="ClassResultSubjectAvg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avg_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average marks (not %).",
                        max_digits=6,
                    ),
                ),
                (
                    "out_of",
                    models.PositiveIntegerField(
                        default=100, help_text="Full marks of the subject."
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_avgs",
                        to="content.classresultsummary",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_avgs",
                        to="content.subject",
                    ),
                ),
            ],
            options={
                "ordering": ("subject__code",),
                "unique_together": {("summary", "subject")},
            },
        ),
    ]
