# Generated by Django 5.2.6 on 2025-09-24 11:46

import content.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0033_alter_classresultsubjectavg_avg_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicclass",
            name="name",
            field=models.CharField(
                help_text='Class name as shown to users, e.g. "Class 8" or "Grade 10".',
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="academicclass",
            name="section",
            field=models.CharField(
                blank=True,
                help_text='Optional section/stream label, e.g. "A", "Science". Leave empty if not used.',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="academicclass",
            name="year",
            field=models.PositiveIntegerField(
                default=2025, help_text="Academic year for this class (e.g., 2025)."
            ),
        ),
        migrations.AlterField(
            model_name="classresultsubjectavg",
            name="avg_score",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Average marks the class scored in this subject.",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="classresultsubjectavg",
            name="out_of",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Maximum possible marks for this subject average (e.g., 100).",
            ),
        ),
        migrations.AlterField(
            model_name="classresultsubjectavg",
            name="subject",
            field=models.ForeignKey(
                help_text="Subject for which you are recording the class average.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="class_avgs",
                to="content.subject",
            ),
        ),
        migrations.AlterField(
            model_name="classresultsubjectavg",
            name="summary",
            field=models.ForeignKey(
                help_text="Select the (Class, Term) summary this average belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_avgs",
                to="content.classresultsummary",
            ),
        ),
        migrations.AlterField(
            model_name="classresultsummary",
            name="appeared",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of students who appeared for the exam in this term.",
            ),
        ),
        migrations.AlterField(
            model_name="classresultsummary",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this summary was created (auto).",
            ),
        ),
        migrations.AlterField(
            model_name="classresultsummary",
            name="highest_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Highest percentage achieved in the class (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="classresultsummary",
            name="klass",
            field=models.ForeignKey(
                help_text="Which class these results belong to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result_summaries",
                to="content.academicclass",
            ),
        ),
        migrations.AlterField(
            model_name="classresultsummary",
            name="lowest_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Lowest percentage achieved in the class (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="classresultsummary",
            name="overall_avg_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Overall average percentage for the class (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="classresultsummary",
            name="pass_rate_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Pass percentage for the class (0–100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="classresultsummary",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Optional notes or remarks shown on the class result page.",
            ),
        ),
        migrations.AlterField(
            model_name="classresultsummary",
            name="term",
            field=models.ForeignKey(
                help_text="Which exam term these results summarize.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result_summaries",
                to="content.examterm",
            ),
        ),
        migrations.AlterField(
            model_name="classresultsummary",
            name="total_students",
            field=models.PositiveIntegerField(
                default=0, help_text="Total students enrolled in the class."
            ),
        ),
        migrations.AlterField(
            model_name="classtopper",
            name="grade",
            field=models.CharField(
                blank=True,
                help_text='Optional grade label, e.g., "A+", "A".',
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="classtopper",
            name="name",
            field=models.CharField(
                help_text="Student full name as it should appear on the site.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="classtopper",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional student profile photo (square crop recommended).",
                null=True,
                upload_to=content.models.upload_student_profile_to,
            ),
        ),
        migrations.AlterField(
            model_name="classtopper",
            name="rank",
            field=models.PositiveIntegerField(
                default=1, help_text="Rank in the class for this term (1 = topper)."
            ),
        ),
        migrations.AlterField(
            model_name="classtopper",
            name="roll_no",
            field=models.CharField(
                blank=True,
                help_text="Optional roll number / ID for reference.",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="classtopper",
            name="summary",
            field=models.ForeignKey(
                help_text="Select the (Class, Term) summary this topper belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="toppers",
                to="content.classresultsummary",
            ),
        ),
        migrations.AlterField(
            model_name="classtopper",
            name="total_pct",
            field=models.DecimalField(
                decimal_places=2, help_text="Overall % (e.g., 92.50).", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="examterm",
            name="name",
            field=models.CharField(
                help_text='Exam term name, e.g. "Midterm", "Final", "Term 1".',
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="examterm",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Optional date when the exam term starts (for reference).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="examterm",
            name="year",
            field=models.PositiveIntegerField(
                default=2025, help_text="Calendar year of the exam term (e.g., 2025)."
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(
                help_text='Short code for the subject, e.g. "ENG", "MATH". Must be unique.',
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="title",
            field=models.CharField(
                help_text='Full subject title as shown to users, e.g. "English", "Mathematics".',
                max_length=120,
            ),
        ),
    ]
