# Generated by Django 5.2.6 on 2025-09-25 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0035_attendancesession_attendancerecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]


    operations = [
        # --- AttendanceSession: replace old unique constraint, add count fields ---
        migrations.RemoveConstraint(
            model_name='attendancesession',
            name='uniq_attendance_session_per_class_day',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='present_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='absent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='late_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='excused_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(
                fields=('school_class', 'date'),
                name='uniq_class_day_session',
            ),
        ),

        # --- AttendanceRecord: drop unique/index sets first, then drop the table ---
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='attendancerecord',
            index_together=set(),
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
