# Generated by Django 5.2.6 on 2025-09-25 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0036_remove_attendancerecord_marked_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(blank=True, max_length=160)),
                (
                    "routine_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="exam_routines/%Y/%m/"
                    ),
                ),
                ("routine_image_url", models.URLField(blank=True, default="")),
                ("exam_start_date", models.DateField()),
                ("exam_end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_routines",
                        to="content.academicclass",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_routines",
                        to="content.examterm",
                    ),
                ),
            ],
            options={
                "ordering": ("-exam_start_date", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("exam_end_date__gte", models.F("exam_start_date")),
                            ("exam_end_date__isnull", True),
                            _connector="OR",
                        ),
                        name="exam_date_range_valid",
                    )
                ],
            },
        ),
    ]
