# Generated by Django 5.2.6 on 2025-09-26 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0037_examroutine"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=120)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Optional short code, e.g. R1",
                        max_length=32,
                    ),
                ),
                ("start_point", models.CharField(blank=True, max_length=200)),
                ("end_point", models.CharField(blank=True, max_length=200)),
                ("operating_days_text", models.CharField(blank=True, max_length=120)),
                ("driver_name", models.CharField(blank=True, max_length=120)),
                ("driver_phone", models.CharField(blank=True, max_length=50)),
                ("assistant_name", models.CharField(blank=True, max_length=120)),
                ("assistant_phone", models.CharField(blank=True, max_length=50)),
                ("vehicle_plate", models.CharField(blank=True, max_length=50)),
                (
                    "vehicle_capacity",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "route_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="bus/routes/%Y/%m/"
                    ),
                ),
                ("route_image_url", models.URLField(blank=True)),
                (
                    "map_embed_src",
                    models.TextField(
                        blank=True, help_text="Google Maps embed URL (optional)"
                    ),
                ),
                ("fare_info", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bus_routes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                ("landmark", models.CharField(blank=True, max_length=200)),
                ("time_text_morning", models.CharField(blank=True, max_length=20)),
                ("time_text_evening", models.CharField(blank=True, max_length=20)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="content.busroute",
                    ),
                ),
            ],
            options={
                "ordering": ("route", "order", "id"),
            },
        ),
    ]
