# Generated by Django 5.2.6 on 2025-09-26 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0038_busroute_busstop"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentMarksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_full_name", models.CharField(max_length=200)),
                (
                    "roll_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("section", models.CharField(blank=True, default="", max_length=50)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_grade",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marksheets",
                        to="content.academicclass",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marksheets",
                        to="content.examterm",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "student_full_name"),
                "unique_together": {
                    ("school_class", "term", "student_full_name", "roll_number")
                },
            },
        ),
        migrations.CreateModel(
            name="StudentMarksheetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "grade_letter",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "marksheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.studentmarksheet",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marksheet_items",
                        to="content.subject",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "unique_together": {("marksheet", "subject")},
            },
        ),
    ]
