# Generated by Django 5.2.6 on 2025-09-27 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0040_alter_classresultsubjectavg_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classresultsubjectavg",
            options={"ordering": ("subject__name",)},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ("school_class", "order", "name")},
        ),
    ]
