# Generated by Django 5.2.6 on 2025-09-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0041_alter_classresultsubjectavg_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
