# Generated by Django 5.2.6 on 2025-09-30 16:39

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0042_alter_subject_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="The latest active record is used site-wide.",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional site title/brand text (fallback if logo missing).",
                        max_length=160,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=content.models.branding_upload_to,
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=content.models.branding_upload_to,
                    ),
                ),
                ("favicon_url", models.URLField(blank=True)),
                (
                    "logo_alt",
                    models.CharField(blank=True, default="Site logo", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Branding",
                "verbose_name_plural": "Site Branding",
                "ordering": ("-updated_at", "-id"),
            },
        ),
    ]
