# Generated by Django 5.2.6 on 2025-10-01 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0043_sitebranding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("fuel", "Fuel Purchase"),
                            ("bus_repair", "Bus Repair"),
                            ("bus_purchase", "Bus Purchase"),
                            ("misc", "Miscellaneous"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admission", "Admission Fee"),
                            ("tuition", "Tuition Fee"),
                            ("exam", "Exam Fee"),
                            ("bus", "Transport/Bus Fee"),
                            ("hostel", "Hostel Fee"),
                            ("marksheet", "Marksheet/Certificate Fee"),
                            ("donation", "Donation/Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
