# Generated by Django 5.2.6 on 2025-10-03 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0045_expensecategory_incomecategory_alter_expense_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="student",
            field=models.ForeignKey(
                blank=True,
                help_text="If this income is for a specific student (tuition, exam, bus, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incomes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=20)),
                ("roll_number", models.PositiveIntegerField()),
                (
                    "joined_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="content.academicclass",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
                "ordering": ("school_class", "section", "roll_number"),
                "unique_together": {("school_class", "section", "roll_number")},
            },
        ),
    ]
