# Generated by Django 5.2.6 on 2025-10-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0046_income_student_studentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="tuitionpayment",
            name="posted_to_ledger",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name="tuitionpayment",
            constraint=models.UniqueConstraint(
                fields=("invoice", "txn_id"), name="uniq_payment_txn_per_invoice"
            ),
        ),
    ]
