# Generated by Django 5.2.6 on 2025-10-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0047_tuitionpayment_posted_to_ledger_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tuitionpayment",
            name="uniq_payment_txn_per_invoice",
        ),
        migrations.AlterField(
            model_name="tuitionpayment",
            name="txn_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddConstraint(
            model_name="tuitionpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("txn_id__isnull", False)),
                fields=("invoice", "txn_id"),
                name="uniq_payment_txn_per_invoice_not_null",
            ),
        ),
    ]
