# Generated by Django 5.2.6 on 2025-10-06 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0048_remove_tuitionpayment_uniq_payment_txn_per_invoice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tuitionpayment",
            name="posted_to_ledger",
        ),
    ]
