# Generated by Django 5.2.6 on 2025-10-06 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0049_remove_tuitionpayment_posted_to_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionapplication",
            name="enroll_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="content.academicclass",
            ),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="enroll_section",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="admissionapplication",
            name="generated_roll",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
