# Generated by Django 5.2.6 on 2025-10-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0050_admissionapplication_enroll_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="monthly_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
