# Generated by Django 5.2.6 on 2025-10-09 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0053_alter_studentprofile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_monthly_fee",
                    models.DecimalField(decimal_places=2, default=2000, max_digits=10),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Finance settings",
            },
        ),
        migrations.AlterModelOptions(
            name="tuitioninvoice",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="tuitioninvoice",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tuitioninvoice",
            name="kind",
            field=models.CharField(
                choices=[("monthly", "Monthly tuition"), ("custom", "Custom")],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tuitioninvoice",
            name="title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="tuitioninvoice",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="tuitioninvoice",
            name="period_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tuitioninvoice",
            name="period_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tuitioninvoice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="tuitioninvoice",
            name="tuition_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name="tuitioninvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "monthly")),
                fields=("student", "kind", "period_year", "period_month"),
                name="uniq_student_monthly_invoice",
            ),
        ),
        migrations.RemoveField(
            model_name="tuitioninvoice",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tuitioninvoice",
            name="notes",
        ),
    ]
