# Generated by Django 5.2.6 on 2025-10-09 18:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0054_financesettings_alter_tuitioninvoice_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tuitioninvoice",
            options={"ordering": ["period_year", "period_month", "id"]},
        ),
        migrations.AddField(
            model_name="tuitioninvoice",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="tuitioninvoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tuitioninvoice",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="tuitioninvoice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tuition_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tuitioninvoice",
            name="tuition_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="tuitionpayment",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("bkash", "bKash"),
                    ("manual", "Manual"),
                ],
                max_length=60,
            ),
        ),
        migrations.AddIndex(
            model_name="tuitioninvoice",
            index=models.Index(
                fields=["student", "kind"], name="content_tui_student_a93c42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tuitioninvoice",
            index=models.Index(
                fields=["period_year", "period_month"],
                name="content_tui_period__64af1e_idx",
            ),
        ),
    ]
