# Generated by Django 5.2.6 on 2025-10-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0055_alter_tuitioninvoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="bus_monthly_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="has_bus_service",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="has_hostel_seat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="hostel_monthly_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
