# Generated by Django 5.2.6 on 2025-10-10 20:50

import content.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0056_studentprofile_bus_monthly_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionapplication",
            name="add_admission",
            field=models.BooleanField(
                default=True,
                editable=False,
                help_text="Always included: Admission fee row.",
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="add_exam",
            field=models.BooleanField(
                default=True, editable=False, help_text="Always included: Exam fee row."
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="add_tuition",
            field=models.BooleanField(
                default=True,
                editable=False,
                help_text="Always included: First Month Tuition row.",
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_admission",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_base_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Admission + First Month Tuition + Exam.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_bus",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_exam",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_hostel",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_marksheet",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Legacy mirror of fee_selected_total.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="fee_tuition",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="payment_provider",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="payment_txn_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Passport-size photo (optional in demo).",
                null=True,
                upload_to=content.models.admission_photo_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="admissionapplication",
            name="transcript",
            field=models.FileField(
                blank=True,
                help_text="Academic transcript/certificate (optional).",
                null=True,
                upload_to=content.models.admission_doc_upload_to,
            ),
        ),
    ]
