# Generated by Django 5.2.6 on 2025-10-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0057_alter_admissionapplication_add_admission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tuitioninvoice",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tuitionpayment",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tuitionpayment",
            name="gateway_payer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="tuitionpayment",
            name="gateway_payer_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="tuitionpayment",
            name="gateway_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tuitionpayment",
            name="gateway_ref",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="tuitionpayment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
