# Generated by Django 5.2.6 on 2025-10-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0058_tuitioninvoice_paid_at_tuitionpayment_gateway_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedGatewayEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "event_id"],
                        name="content_pro_provide_b0a6e6_idx",
                    )
                ],
            },
        ),
    ]
