# Generated by Django 5.2.6 on 2025-10-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0059_processedgatewayevent"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tuitionpayment",
            name="uniq_payment_txn_per_invoice_not_null",
        ),
        migrations.AddConstraint(
            model_name="tuitionpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("txn_id__isnull", False)),
                fields=("invoice", "txn_id", "provider", "gateway_ref"),
                name="uniq_payment_txn_per_invoice_not_null",
            ),
        ),
    ]
