# Generated by Django 5.2.6 on 2025-10-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0061_commslog_emailbounce_messagetemplate_emailoutbox_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmarksheet",
            name="is_pass",
            field=models.BooleanField(default=False),
        ),
    ]
