# Generated by Django 5.2.6 on 2025-10-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0062_studentmarksheet_is_pass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmarksheet",
            name="is_pass",
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
